services:
  gpt-sovits-api:
    image: 1.82.180.74:5000/gpt-sovits-api:latest
    container_name: gpt-sovits-api
    ports:
      - "9880:9880"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - CUDA_VISIBLE_DEVICES=0,1,2,3
      - DEVICE=cuda
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    shm_size: "16g"
    tty: true
    stdin_open: true 