custom:
  bert_base_path: GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large
  cnhuhbert_base_path: GPT_SoVITS/pretrained_models/chinese-hubert-base
  device: cuda:0
  is_half: true
  t2s_weights_path: GPT_SoVITS/pretrained_models/s1v3.ckpt
  version: v4
  vits_weights_path: GPT_SoVITS/pretrained_models/gsv-v4-pretrained/s2Gv4.pth
  # CUDA优化配置
  use_vocoder_optimization: true
  vocoder_chunk_size: 400
  vocoder_overlap_ratio: 0.05
  # 并发处理配置
  enable_concurrent_tts: true
  num_gpus: 4
v1:
  bert_base_path: GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large
  cnhuhbert_base_path: GPT_SoVITS/pretrained_models/chinese-hubert-base
  device: cuda:0
  is_half: true
  t2s_weights_path: GPT_SoVITS/pretrained_models/s1bert25hz-2kh-longer-epoch=68e-step=50232.ckpt
  version: v1
  vits_weights_path: GPT_SoVITS/pretrained_models/s2G488k.pth
  # CUDA优化配置
  use_vocoder_optimization: true
  vocoder_chunk_size: 400
  vocoder_overlap_ratio: 0.05
  # 并发处理配置
  enable_concurrent_tts: true
  num_gpus: 4
v2:
  bert_base_path: GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large
  cnhuhbert_base_path: GPT_SoVITS/pretrained_models/chinese-hubert-base
  device: cuda:0
  is_half: true
  t2s_weights_path: GPT_SoVITS/pretrained_models/gsv-v2final-pretrained/s1bert25hz-5kh-longer-epoch=12-step=369668.ckpt
  version: v2
  vits_weights_path: GPT_SoVITS/pretrained_models/gsv-v2final-pretrained/s2G2333k.pth
  # CUDA优化配置
  use_vocoder_optimization: true
  vocoder_chunk_size: 400
  vocoder_overlap_ratio: 0.05
  # 并发处理配置
  enable_concurrent_tts: true
  num_gpus: 4
v2Pro:
  bert_base_path: GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large
  cnhuhbert_base_path: GPT_SoVITS/pretrained_models/chinese-hubert-base
  device: cuda:0
  is_half: true
  t2s_weights_path: GPT_SoVITS/pretrained_models/s1v3.ckpt
  version: v2Pro
  vits_weights_path: GPT_SoVITS/pretrained_models/v2Pro/s2Gv2Pro.pth
  # CUDA优化配置
  use_vocoder_optimization: true
  vocoder_chunk_size: 400
  vocoder_overlap_ratio: 0.05
  # 并发处理配置
  enable_concurrent_tts: true
  num_gpus: 4
v2ProPlus:
  bert_base_path: GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large
  cnhuhbert_base_path: GPT_SoVITS/pretrained_models/chinese-hubert-base
  device: cuda:0
  is_half: true
  t2s_weights_path: GPT_SoVITS/pretrained_models/s1v3.ckpt
  version: v2ProPlus
  vits_weights_path: GPT_SoVITS/pretrained_models/v2Pro/s2Gv2ProPlus.pth
  # CUDA优化配置
  use_vocoder_optimization: true
  vocoder_chunk_size: 400
  vocoder_overlap_ratio: 0.05
  # 并发处理配置
  enable_concurrent_tts: true
  num_gpus: 4
v3:
  bert_base_path: GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large
  cnhuhbert_base_path: GPT_SoVITS/pretrained_models/chinese-hubert-base
  device: cuda:0
  is_half: true
  t2s_weights_path: GPT_SoVITS/pretrained_models/s1v3.ckpt
  version: v3
  vits_weights_path: GPT_SoVITS/pretrained_models/s2Gv3.pth
  # CUDA优化配置
  use_vocoder_optimization: true
  vocoder_chunk_size: 400
  vocoder_overlap_ratio: 0.05
  # 并发处理配置
  enable_concurrent_tts: true
  num_gpus: 4
v4:
  bert_base_path: GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large
  cnhuhbert_base_path: GPT_SoVITS/pretrained_models/chinese-hubert-base
  device: cuda:0
  is_half: true
  t2s_weights_path: GPT_SoVITS/pretrained_models/s1v3.ckpt
  version: v4
  vits_weights_path: GPT_SoVITS/pretrained_models/gsv-v4-pretrained/s2Gv4.pth
  # CUDA优化配置
  use_vocoder_optimization: true
  vocoder_chunk_size: 400
  vocoder_overlap_ratio: 0.05
  # 并发处理配置
  enable_concurrent_tts: true
  num_gpus: 4
